name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: ls -la
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tomondre/notes-page:${{ github.run_number }}

  CD:
    runs-on: self-hosted
    needs: CI
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Terraform Initialize
        working-directory: infrastructure
        run: terraform init
      - name: Terraform apply
        working-directory: infrastructure
        run: terraform apply -auto-approve -var "image_tag={{ github.run_number }}"
